### ISSUE TITLE
Архитектура переходов состояний в Telegram боте

### ISSUE THREAD

**Issue by dura0ok** [dura0ok/Concerts-Suggester#7]
![изображение](https://github.com/dura0ok/Concerts-Suggester/assets/28489754/26f7da0b-815c-4897-a617-4ab4fa0f1f6c)
Нарисовать диаграмму типо такого где будут виден каждый переход

**Comment by Wooshey1411** [comment]
![image](https://github.com/dura0ok/Concerts-Suggester/assets/113329986/9c26ab83-4187-49b6-a371-1072ed069093)
В Miro построил

**Comment by dura0ok** [comment]
Одобряем? @llirik42 @pipichinka

**Comment by llirik42** [comment]
Отлично
Вопросы лишь в расширение
Что будет ссылка на плейлисты или будет ещё радиус (для города)
Или ссылка не на плейлист, а на альбом
Но в целом всё норм
Или возможность оплаты для дополнительных услуг

**Comment by dura0ok** [comment]
Почему issue зависло?

**Comment by llirik42** [comment]
@dura0ok, а зачем меня упоминать? Я же сказал, что всё отлично.

**Comment by dura0ok** [comment]
Я хочу быть в курсе

**Comment by dura0ok** [comment]
Сделай пинок..
